---
- name: Upgrade the OS IF it is less than 6
  ansible.builtin.dnf:
    name: '*'
    state: latest
  become: yes
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") 
